name: 'Openfire Start Server'
description: 'Start CI server from distribution'
inputs:
  distbasedir:
    description: 'The base directory of the Openfire installation that isto be started.'
    required: false
    default: './distribution/target/distribution=base/'
  debug:
    description: 'Enable debug mode. Prints commands, and preserves temp directories if used.'
    required: false
    default: 'false'
  domain:
    description: 'XMPP domain name of server.'
    required: false
    default: 'example.org'
  ip:
    description: 'Set a hosts file for the given IP and host (or for example.com if running locally)'
    required: false
    default: '127.0.0.1'

runs:
  using: "composite"
  steps:
    - run: bash ./startCIServer.sh -d -l -i ${{ inputs.ip }} -h ${{ inputs.domain }} -b ${{ inputs.distbasedir }}
      shell: bash
